---
deployment:
  tasks:
    - export DEPLOYPATH=/home/us7gxzgi/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp config.php $DEPLOYPATH
    - /bin/cp home.php $DEPLOYPATH
    - /bin/cp Main.php $DEPLOYPATH
    - /bin/cp -R /assets/images $DEPLOYPATH